name: Deploy to EC2 🚀

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "${{ secrets.SSH_KNOWN_HOST }}" > ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
          cd /home/ubuntu

          # Clone project if not exists
          if [ ! -d "parkmeter-server" ]; then
            git clone https://github.com/pratikkoradur-stack/parkmeter-2.git parkmeter-server
          fi

          cd parkmeter-server

          git pull origin main
          npm install

          pm2 restart parkmeter || pm2 start index.js --name parkmeter
          pm2 save
          EOF
